### ISSUE TITLE
Conversion Reference is bad or needs clarify in the documentation 

### ISSUE THREAD

**Issue by elo24o** [PerformanceHorizonGroup/partnerize-mobile-sdk-android#2]
Hi, today I'm implementing your SDK in an app but when I send the URL generated by the SDK the Partnerize console not recognize my conversion reference. Talking with the support they say 

> This needs to be sent through as 'conversionref:' in the tracking call.

But the SDK generates a URL with 

> 'conversion_reference:'

Can you provide a solution for that adding that case in the documentation or changing the implementation? I lost a spend time thinking that is my error.

**Comment by jb0o** [comment]
Hi elo24o,

Thanks for raising this to us.

I've checked in with the engineering team and this is indeed an unsupported parameter.

You can get around this right now by utilising the meta data property like below;

`conversion.addMetadata("conversionref", "CONVERSION_REF_HERE");`

I'll get this raised as a bug internally and ensure this is fixed as soon as possible and pushed out in a new release.

Many thanks,
JB

**Comment by jb0o** [comment]
This has now been resolved as part of https://github.com/PerformanceHorizonGroup/partnerize-mobile-sdk-android/releases/tag/v1.3.
